export type Agent = {
  id: string;
  created_at: string | null;
  updated_at: string | null;
  client_id: string;
  created_by: string | null;
  name: string;
  description: string | null;
  status: string;
  role: string | null;
  avatar_color: string | null;
  company_context: string | null;
  objective: string | null;
  persona: string | null;
  greeting: string | null;
  system_prompt: string | null;
  knowledge_base: string | null;
  guardrails: string | null;
  escalation_instructions: string | null;
  voice_provider: string | null;
  voice_id: string | null;
  language: string | null;
  voicemail_message: string | null;
  transfer_phone: string | null;
  max_call_seconds: number | null;
  model: string | null;
  temperature: number | string | null;
  metadata: Record<string, unknown> | null;
};
